-- EllencoCheck + Supabase
-- Execute este arquivo no SQL Editor do seu projeto Supabase.
-- Depois de criar a primeira conta pelo site, torne-a administradora:
-- UPDATE public.profiles SET role = 'admin' WHERE email = 'seu@email.com';

create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    nome text not null,
    email text not null,
    ativo boolean not null default true,
    role text not null default 'user' check (role in ('user','admin')),
    criado_em timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, nome, email)
    values (
        new.id,
        coalesce(nullif(new.raw_user_meta_data->>'nome',''), split_part(new.email,'@',1)),
        lower(new.email)
    )
    on conflict (id) do update set
        email = excluded.email;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
    select exists (
        select 1 from public.profiles
        where id = auth.uid() and role = 'admin' and ativo = true
    );
$$;

create table if not exists public.tipos_equipamentos (
    id bigint generated by default as identity primary key,
    nome text not null unique,
    descricao text,
    ativo boolean not null default true
);

create table if not exists public.equipamentos (
    id bigint generated by default as identity primary key,
    tipo_id bigint not null references public.tipos_equipamentos(id),
    nome text not null,
    patrimonio text unique,
    modelo text,
    fabricante text,
    placa text,
    ano integer,
    horimetro numeric(10,2) not null default 0,
    status text not null default 'ATIVO' check (status in ('ATIVO','MANUTENCAO','INATIVO')),
    observacoes text,
    ativo boolean not null default true,
    criado_em timestamptz not null default now(),
    atualizado_em timestamptz not null default now()
);

create or replace function public.atualizar_equipamento_timestamp()
returns trigger
language plpgsql
as $$
begin
    new.atualizado_em = now();
    return new;
end;
$$;

drop trigger if exists equipamentos_updated_at on public.equipamentos;
create trigger equipamentos_updated_at
before update on public.equipamentos
for each row execute procedure public.atualizar_equipamento_timestamp();

create table if not exists public.itens_inspecao (
    id bigint generated by default as identity primary key,
    tipo_id bigint not null references public.tipos_equipamentos(id),
    nome text not null,
    descricao text,
    categoria text not null default 'Geral',
    ordem integer not null default 0,
    obrigatorio boolean not null default true,
    ativo boolean not null default true
);

create table if not exists public.checklists (
    id bigint generated by default as identity primary key,
    equipamento_id bigint not null references public.equipamentos(id),
    usuario_id uuid not null references public.profiles(id),
    horimetro numeric(10,2) not null default 0,
    status text not null check (status in ('APROVADO','APROVADO_COM_OBSERVACAO','REPROVADO')),
    observacoes text,
    realizado_em timestamptz not null default now()
);

create table if not exists public.respostas_checklist (
    id bigint generated by default as identity primary key,
    checklist_id bigint not null references public.checklists(id) on delete cascade,
    item_inspecao_id bigint not null references public.itens_inspecao(id),
    status text not null check (status in ('OK','ATENCAO','PROBLEMA','NAO_APLICAVEL')),
    observacao text,
    foto_nome text,
    respondido_em timestamptz not null default now(),
    unique (checklist_id, item_inspecao_id)
);

create index if not exists idx_checklists_equipamento on public.checklists(equipamento_id);
create index if not exists idx_checklists_usuario on public.checklists(usuario_id);
create index if not exists idx_itens_tipo on public.itens_inspecao(tipo_id);

-- RLS
alter table public.profiles enable row level security;
alter table public.tipos_equipamentos enable row level security;
alter table public.equipamentos enable row level security;
alter table public.itens_inspecao enable row level security;
alter table public.checklists enable row level security;
alter table public.respostas_checklist enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles
for insert to authenticated
with check (id = auth.uid());

create or replace function public.protect_profile_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_admin() then
        if new.role <> old.role or new.ativo <> old.ativo or new.id <> old.id then
            raise exception 'Somente administradores podem alterar função ou status do usuário.';
        end if;
    end if;
    return new;
end;
$$;

drop trigger if exists protect_profile_fields_trigger on public.profiles;
create trigger protect_profile_fields_trigger
before update on public.profiles
for each row execute procedure public.protect_profile_fields();

drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles
for update to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

drop policy if exists tipos_select on public.tipos_equipamentos;
create policy tipos_select on public.tipos_equipamentos
for select to authenticated using (ativo = true or public.is_admin());

drop policy if exists equipamentos_select on public.equipamentos;
create policy equipamentos_select on public.equipamentos
for select to authenticated using (ativo = true or public.is_admin());

drop policy if exists itens_select on public.itens_inspecao;
create policy itens_select on public.itens_inspecao
for select to authenticated using (ativo = true or public.is_admin());

drop policy if exists checklists_select on public.checklists;
create policy checklists_select on public.checklists
for select to authenticated
using (usuario_id = auth.uid() or public.is_admin());

drop policy if exists checklists_insert on public.checklists;
create policy checklists_insert on public.checklists
for insert to authenticated
with check (usuario_id = auth.uid());


drop policy if exists checklists_delete on public.checklists;
create policy checklists_delete on public.checklists
for delete to authenticated
using (usuario_id = auth.uid() or public.is_admin());

drop policy if exists respostas_select on public.respostas_checklist;
create policy respostas_select on public.respostas_checklist
for select to authenticated
using (
    exists (
        select 1 from public.checklists c
        where c.id = checklist_id
          and (c.usuario_id = auth.uid() or public.is_admin())
    )
);

drop policy if exists respostas_insert on public.respostas_checklist;
create policy respostas_insert on public.respostas_checklist
for insert to authenticated
with check (
    exists (
        select 1 from public.checklists c
        where c.id = checklist_id
          and c.usuario_id = auth.uid()
    )
);

-- Seeds
insert into public.tipos_equipamentos (id,nome,descricao,ativo) values
(1,'Escavadeira','Máquina para escavação e movimentação de materiais',true),
(2,'Retroescavadeira','Equipamento para escavação e carregamento',true),
(3,'Pá Carregadeira','Máquina para carregamento e movimentação',true),
(4,'Motoniveladora','Máquina para nivelamento de terrenos',true),
(5,'Rolo Compactador','Equipamento para compactação',true)
on conflict (id) do update set
    nome = excluded.nome, descricao = excluded.descricao, ativo = excluded.ativo;

insert into public.equipamentos
(id,tipo_id,nome,patrimonio,modelo,fabricante,horimetro,status,ativo) values
(1,1,'Escavadeira 01','EQ-001','320','Caterpillar',1250.50,'ATIVO',true),
(2,2,'Retroescavadeira 01','EQ-002','416F2','Caterpillar',980.20,'ATIVO',true)
on conflict (id) do update set
    tipo_id=excluded.tipo_id, nome=excluded.nome, patrimonio=excluded.patrimonio,
    modelo=excluded.modelo, fabricante=excluded.fabricante, horimetro=excluded.horimetro,
    status=excluded.status, ativo=excluded.ativo;

insert into public.itens_inspecao
(id,tipo_id,nome,descricao,categoria,ordem,obrigatorio,ativo) values
(1,1,'Nível do óleo do motor','Verificar se o nível está adequado.','Motor',1,true,true),
(2,2,'Nível do óleo do motor','Verificar se o nível está adequado.','Motor',1,true,true),
(4,1,'Nível do líquido de arrefecimento','Verificar nível e sinais de vazamento.','Motor',2,true,true),
(5,1,'Vazamentos hidráulicos','Verificar mangueiras, conexões e cilindros.','Hidráulica',3,true,true),
(6,1,'Estado das esteiras','Verificar desgaste, tensão e danos.','Material Rodante',4,true,true),
(7,2,'Pneus','Verificar calibragem, desgaste e danos.','Rodagem',2,true,true)
on conflict (id) do update set
    tipo_id=excluded.tipo_id, nome=excluded.nome, descricao=excluded.descricao,
    categoria=excluded.categoria, ordem=excluded.ordem, obrigatorio=excluded.obrigatorio,
    ativo=excluded.ativo;

-- Permissões de sequência após seeds com IDs explícitos
select setval(pg_get_serial_sequence('public.tipos_equipamentos','id'),
              greatest(coalesce((select max(id) from public.tipos_equipamentos),1),1), true);
select setval(pg_get_serial_sequence('public.equipamentos','id'),
              greatest(coalesce((select max(id) from public.equipamentos),1),1), true);
select setval(pg_get_serial_sequence('public.itens_inspecao','id'),
              greatest(coalesce((select max(id) from public.itens_inspecao),1),1), true);
